/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CompresorGrafico;

import ClasesCompresor.*;
import javax.swing.*;
import java.io.*;
/**
 * Esta es la clase Compresor donde se encuentra la interfaz grafica del proyecto y en la cual se mandan a llamar los metodos
 * de otras clases.
 * @author Ingrid Niño, Zuleyka Guzman
 */
public class Compresor extends javax.swing.JFrame {
    /**
     * Esta es la variable la que es una instancia de la clase ColaArboles
     */
    ColaArboles la = new ColaArboles();
    /**
     * Esta es la variable tabla que es una instancia de la clase ListaTabla
     */
    private ListaTabla tabla = new ListaTabla();
    /**
     * Creates new form EncriptarDesencriptar
     */
    public Compresor() {
        initComponents();
        this.setTitle("Encriptador");
        this.setResizable(false);
        this.setIconImage(new ImageIcon(getClass().getResource("../Imagenes/locked.png")).getImage());
    }

    /**
     * This method is ca
     * lled from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/g1.png"))); // NOI18N
        jButton1.setText("GUARDAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 130, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DESCOMPRIMIR.png"))); // NOI18N
        jButton2.setText("DESCOMPRIMIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/COMPRIMIR.png"))); // NOI18N
        jButton3.setText("COMPRIMIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 140, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUSCAR.png"))); // NOI18N
        jButton4.setText("SELECCIONAR ARCHIVO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 180, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 180, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDO.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "EL ARCHIVO SE GUARDO CORRECTAMENTE");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(null, "DESCOMPRIMIDO CORRECTAMENTE");
    }//GEN-LAST:event_jButton2ActionPerformed
/**
 * Este metodo nos sirve para seleccionar nuestro archivo txt a comprimir 
 * @param evt 
 */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.setVisible(true);
        jf.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int opcion = jf.showOpenDialog(jButton1);
                        if (opcion == jf.APPROVE_OPTION) {
                        String pathArchivo = jf.getSelectedFile().getPath();
                        String nombre = jf.getSelectedFile().getName(); 
                            jLabel2.setText(nombre);
                            jLabel3.setText(pathArchivo);
                        }
    }//GEN-LAST:event_jButton4ActionPerformed
/**
 * En este metodo se lee el archivo a comprimir y se lanza una excepcion en caso de no haber seleccionado el archivo
 * @param evt 
 */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ColaArboles cola=new ColaArboles();
        String nomArchivo=jLabel3.getText();
        try{            
            FileReader c = new FileReader(nomArchivo);
                    int caracter;
                    caracter = c.read();
                    
                    while(caracter != -1) {
                        Caracter car = new Caracter ((char)caracter,1);
                        NodoA nc=new NodoA(car);
                        ArbolBinario ab=new ArbolBinario();
                        ab.setRaiz(nc);
                        cola.agregar(ab); 
                        caracter = c.read();
                    }
                    
                    c.close();
                    cola.contarCaracteres(la); 
                    //System.out.println(la.recorrer());
                    cola.setCabecera(null);
                    la.obtenerNodos();
                    //System.out.println(la.recorrer());
                    //la.getCabecera().getDato().preOrden();
                    tabla = la.contarHojas("", tabla, la.getCabecera().getDato().getRaiz());
                    System.out.println(tabla.imprimir());
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, "AÚN NO HAS SELECCIONADO NINGUN ARCHIVO", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compresor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compresor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compresor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compresor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compresor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
